language: elixir
otp_release:
  - 19.0
elixir:
  - 1.3
  - 1.4
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database shield_test;' -U postgres
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.create -r Authable.Repo, ecto.migrate -r Authable.Repo