language: elixir
otp_release:
  - 19.0
elixir:
  - 1.2.4
  - 1.3
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database authable_test;' -U postgres
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.create, ecto.migrate -r Authable.Repo